# Generated by Django 5.1.1 on 2025-05-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/'),
        ),
    ]
