# Generated by Django 5.1.1 on 2025-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_maincontent_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='django2025/images/%Y/%m/%d/'),
        ),
    ]
